# Generated by Django 3.2.18 on 2023-06-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medley', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medley',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='medley',
            name='user_profile',
        ),
    ]
