# Generated by Django 3.2.18 on 2023-07-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medley', '0003_medley_random'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medley_random',
        ),
    ]
