# Generated by Django 3.2.18 on 2023-03-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footnote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footnote',
            old_name='post',
            new_name='idea',
        ),
    ]
