# Generated by Django 3.2.18 on 2023-03-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footnote', '0003_auto_20230318_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=280)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.DeleteModel(
            name='Medley',
        ),
    ]
