# Generated by Django 3.2.18 on 2023-03-18 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('footnote', '0004_auto_20230318_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Writer',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='idea',
        ),
        migrations.AlterField(
            model_name='footnote',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='footnote_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='idea_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
