# Generated by Django 3.2.18 on 2023-06-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footnote', '0005_auto_20230318_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='footnote',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
