# Generated by Django 3.2.18 on 2023-06-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footnote', '0006_footnote_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footnote',
            old_name='body',
            new_name='content',
        ),
    ]
