# Generated by Django 3.2.18 on 2023-06-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footnote', '0007_rename_body_footnote_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootNoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('footnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='footnote.footnote')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footnote.idea')),
            ],
        ),
    ]
