# Generated by Django 3.2.18 on 2023-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footnote', '0008_footnotelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='footnote',
            name='footnote_number',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='footnote',
            name='footnote_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
