# Generated by Django 3.2.18 on 2023-06-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writer_profile', '0001_initial'),
        ('footnote', '0009_auto_20230621_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='footnote',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writerprofile', to='writer_profile.writerprofile'),
        ),
    ]
