# Generated by Django 3.2.18 on 2023-06-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footnote', '0011_auto_20230624_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
