# Generated by Django 3.2.18 on 2023-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footnote', '0012_idea_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
