# Generated by Django 3.2.18 on 2023-06-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writer_profile', '0001_initial'),
        ('footnote', '0014_remove_footnote_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writerprofileidea', to='writer_profile.writerprofile'),
        ),
    ]
