# Generated by Django 3.2.18 on 2023-07-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footnote', '0015_idea_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footnote',
            name='email',
        ),
    ]
