# Generated by Django 3.2.18 on 2023-06-21 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_gender', models.CharField(blank=True, max_length=30, null=True)),
                ('default_town_or_city', models.CharField(blank=True, max_length=30, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('default_writingtype', models.CharField(blank=True, max_length=60, null=True)),
                ('default_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('default_favouriteauthor', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
